---
# Configuration file for running ChIP-seq workflow

# Here is where the reference genomes are specified
reference:
    # name of the genome
    U00096.3:
        # location of the genbanks. If put in the location and format shown
        # below the pipeline will attempt to pull this file from NCBI by
        # accession number
        genbanks: 
                - resources/genbanks/U00096.3.gbk
        # This is the fasta file for each chromosome in the genome
        # If specified in this location then it is automatically parsed
        # from the genbank.
        fastas:
                - results/alignment/process_genbank/U00096.3/U00096.3.fna
        # This is the expected total size in basepair of the final genome
        genome_size: 4641652

# Options to control genome coverage calculations
coverage:
    # what resolution in bp do you want the coverage to be calculated?
    resolution: 5

# Options to control normalization of coverage signals
normalization:
    # how to normalize within a sample. Options include:
    # RPKM, CPM, BPM, RPGC, median, and SES. See deeptools manual for
    # details on these normalization methods.
    within: median
    # Robust Z scale the log2ratio of extracted to input
    RobustZ: true

# Options to control quality control
quality_control:
    # what column to group samples by for ChIP-QC output plots?
    group_by: genome

# Options to control peak calling
peak_calling:
    # Options that control CMARRT calling
    cmarrt:
        # Can specify individual parameters based on a column
        group_by: genome
        # for each value in the column specify the parameters
        U00096.3:
            # Half the size of the window in *entries* thus this would be 25
            # * 5 bp resolution for a half window size of 125 bp
            wi: 25
            # Number of entries to consolidate peaks over i.e. two peaks within
            # 10 * 5bp = 50 bp will get merged into one peak.
            consolidate: 10
    macs2:
        group_by: genome
        U00096.3:
            # call broad peaks?
            broad: true


# parameters for summary plots

gffs:
    GeneProducts: "/mnt/scratch/mbwolfe/genomes/regulondb/GeneProductSet_U00096_3.bed"
    Operons: "/mnt/scratch/mbwolfe/genomes/regulondb/OperonSet_U00096_3.bed"
    rRNAs: "/mnt/scratch/mbwolfe/genomes/regulondb/rRNASet_U00096_3.bed"
    sRNAs: "/mnt/scratch/mbwolfe/genomes/regulondb/sRNASet_U00096_3.bed"
    tRNAs: "/mnt/scratch/mbwolfe/genomes/regulondb/tRNASet_U00096_3.bed"
    Rel_SC: "annotations/supercoiling/RelSC_GeneProductSet_U00096_3.bed"
    Hyp_SC: "annotations/supercoiling/HypSC_GeneProductSet_U00096_3.bed"
    HighExp: "annotations/expression/HighExpression_U00096_3.bed"
    LowExp: "annotations/expression/LowExpression_U00096_3.bed"
    PromoterProximal: "annotations/regulator_trafficking/PromoterProximal_U00096_3.bed"
    NoPromoterProximal: "annotations/regulator_trafficking/NoPromoterProximal_U00096_3.bed"
    HQ_TUs: "annotations/regulator_trafficking/HQ_TUs_U00096_3.bed"
    HE_HQ_TUs: "annotations/regulator_trafficking/HE_HQ_TUs_U00096_3.bed"
    nusG_rac_BSTs: "annotations/termination/BSTs_nusg_rac_U00096_3.bed"
    nusG_MDS42_BSTs: "annotations/termination/BSTs_nusg_mds42_U00096_3.bed"
    SEndseq_TUs: "annotations/sendseq/SEndseq_TUs_U00096_3.bed"

