---
# Configuration file for running ChIP-seq workflow

# Here is where the reference genomes are specified
reference:
    # name of the genome
    U00096.3:
        # location of the genbanks. If put in the location and format shown
        # below the pipeline will attempt to pull this file from NCBI by
        # accession number
        genbanks: 
            U00096.3: resources/genbanks/U00096.3.gbk
        # This is the fasta file for each chromosome in the genome
        # If specified in this location then it is automatically parsed
        # from the genbank.
        fastas:
            - results/alignment/process_genbank/U00096.3/U00096.3.fna
        masked_regions: test/ecoli_rrns.bed
    ZM4:
        genbanks:
            ZM4: resources/genbanks/CP023715.1.gbk
            pZM32: resources/genbanks/CP023716.1.gbk
            pZM33: resources/genbanks/CP023717.1.gbk
            pZM36: resources/genbanks/CP023718.1.gbk
            pZM39: resources/genbanks/CP023719.1.gbk
        fastas:
            - results/alignment/process_genbank/ZM4/ZM4.fna
            - results/alignment/process_genbank/ZM4/pZM32.fna
            - results/alignment/process_genbank/ZM4/pZM33.fna
            - results/alignment/process_genbank/ZM4/pZM36.fna
            - results/alignment/process_genbank/ZM4/pZM39.fna
# Options to control genome coverage calculations
coverage:
    # what resolution in bp do you want the coverage to be calculated?
    resolution: 5

# Options to control normalization of coverage signals
normalization:
    # how to normalize within a sample. Options include:
    # RPKM, CPM, BPM, RPGC, median, and SES. See deeptools manual for
    # details on these normalization methods.
    within: median
    # Robust Z scale the log2ratio of extracted to input
    RobustZ: true

# Options to control quality control
quality_control:
    # what column to group samples by for ChIP-QC output plots?
    group_by: genome

# Options to control peak calling
peak_calling:
        # Options that control CMARRT calling
    cmarrt:
            # Can specify individual parameters based on a column
        group_by: genome
            # for each value in the column specify the parameters
        U00096.3:
                # Half the size of the window in *entries* thus this would be 25
                # * 5 bp resolution for a half window size of 125 bp
            wi: 25
                # Number of entries to consolidate peaks over i.e. two peaks within
                # 10 * 5bp = 50 bp will get merged into one peak.
            consolidate: 10
        ZM4:
                # Half the size of the window in *entries* thus this would be 25
                # * 5 bp resolution for a half window size of 125 bp
            wi: 25
                # Number of entries to consolidate peaks over i.e. two peaks within
                # 10 * 5bp = 50 bp will get merged into one peak.
            consolidate: 10
    macs2:
        group_by: genome
        U00096.3:
            # call broad peaks?
            broad: true
        ZM4:
            # call broad peaks?
            broad: false
