---
# Configuration file for running ChIP-seq workflow

# Here is where the reference genomes are specified
reference:
    # name of the genome
    U00096.3:
        # location of the genbanks. If put in the location and format shown
        # below the pipeline will attempt to pull this file from NCBI by
        # accession number. Each genbank MUST have a associated name which
        # is used to name the contig pulled from it.
        genbanks: 
            U00096.3: resources/genbanks/U00096.3.gbk
        # This is the fasta file for each chromosome in the genome
        # If specified location then it is automatically parsed
        # from the genbank.
        fastas:
            - results/alignment/process_genbank/U00096.3/U00096.3.fna
            # but you can also add additional contigs that you may want in
            # the final alignment genome by listing them here
            - test/ecoli_rrnD.fa
        masked_regions: test/ecoli_rrns.bed

# Options to control preprocessing rules
preprocessing:
    cutadapt_pe:
        cut_param_string:
            value: "-a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
    trimmomatic_pe:
        trim_param_string:
            value: "LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15"

# Options to control alignment rules
alignment:
    process_genbank:
        features:
            value: "CDS tRNA rRNA ncRNA"
        qual_name: 
            value: "gene"

    bowtie2_map:
        bowtie2_param_string:
            value: "--end-to-end --very-sensitive --phred33"
        samtools_view_param_string:
            value: "-b"


# Options to control genome coverage calculations
coverage_and_norm:
    # general controls
    # what resolution in bp do you want the coverage to be calculated?
    resolution: 5
    # how to normalize within a sample. Options include:
    # RPKM, CPM, BPM, RPGC, median, and SES. See deeptools manual for
    # details on these normalization methods.
    within: median
    # drop NaNs and Infs from zero coverage in input or extracted
    # Note
    # that bigwigs will not display properly in IGV if they have nans or infs
    dropNaNsandInfs: true
    # Robust Z scale the log2ratio of extracted to input
    RobustZ: true
    # rule specific controls
    deeptools_coverage:
        bamCoverage_param_string:
            value: "--samFlagInclude 66 --extendReads --exactScaling --minMappingQuality 10"
    bwtools_median:
        pseudocount:
            value: 1
    bwtools_background_subtract:
        background_regions: 
            value: "results/alignment/process_genbank/U00096.3/U00096.3.bed"
    bwtools_query_subtract:
        query_regions:
            value: "results/alignment/process_genbank/U00096.3/U00096.3.bed"
        number_of_regions:
            value: 20
    bwtools_query_scale:
        query_regions:
            value: "results/alignment/process_genbank/U00096.3/U00096.3.bed"
        number_of_regions:
            value: 20

# Options to control quality control
quality_control:
    # what column to group samples by for ChIP-QC output plots?
    group_by: genome

# Options to control peak calling
peak_calling:
        # Options that control CMARRT calling
    cmarrt:
            # Can specify individual parameters based on a column
        group_by: genome
            # for each value in the column specify the parameters
        U00096.3:
                # Half the size of the window in *entries* thus this would be 25
                # * 5 bp resolution for a half window size of 125 bp
            wi: 25
                # Number of entries to consolidate peaks over i.e. two peaks within
                # 10 * 5bp = 50 bp will get merged into one peak.
            consolidate: 10
    macs2:
        group_by: genome
        U00096.3:
            # call broad peaks?
            broad: true

postprocessing:
    bwtools_byregion:
        all_genes:
            regions: "results/alignment/process_genbank/U00096.3/U00096.3.bed"
            filesignature: "results/coverage_and_norm/deeptools_log2ratio/%s_median_log2ratio_querysub_queryscale.bw"
